### ISSUE TITLE
{环境配置}Dockerfile创建的镜像层数太多了

### ISSUE THREAD

**Issue by Aya99code** [nkucs/JudgeServer#1]
>之前说过，Dockerfile 中每一个指令都会建立一层，RUN 也不例外。每一个 RUN 的行为，就和刚才我们手工建立镜像的过程一样：新建立一层，在其上执行这些命令，执行结束后，commit 这一层的修改，构成新的镜像。而上面的这种写法，创建了 7 层镜像。这是完全没有意义的，而且很多运行时不需要的东西，都被装进了镜像里，比如编译环境、更新的软件包等等。结果就是产生非常臃肿、非常多层的镜像，不仅仅增加了构建部署的时间，也很容易出错。

参考[这里](https://docker_practice.gitee.io/image/build.html)把Dockerfile里那一堆RUN指令精简一下吧

@NeeXxx

**Comment by NeeXxx** [comment]
好的，之前写多个RUN指令正是出于多层镜像的考虑，因为担心某一指令的失败导致整个镜像的rebuild
（另外，在校网环境下安装pip包有可能出现hashsum mismatch的错误）
关于部署时间过长，Dockerfile里已经修改了国内镜像，比起原始的部署速度已经大大加快

**Comment by Aya99code** [comment]
- 我是看到mkdir都要新建一层镜像觉得没必要，我去查了一下原本的青岛大学的OJ他们那边Dockerfile是和我的意思一样只有一个RUN指令，这个还是根据你们的具体实际情况来吧。
- 啊如果pip安装依赖总是有问题的话可以考虑用python3.7自带的那个venv把需要的依赖提前下载保存至本地venv文件，再让venv文件挂载到容器里，就不用每次重新下载了。这个也根据你们那边的实际情况看吧。

此issue终结吧，辛苦你萌啦
